name: Check dict update

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Create dictionary
      run: |
        python mong/create_dict.py
    - name: Check diff
      run: |
        git diff --exit-code mong/moby_dict.json
