name: check dict update

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Create dictionary
      run: |
        python mong/create_dict.py
    - name: Check diff
      run: |
        git diff --exit-code mong/moby_dict.json
