name: Publish Python distributions to TestPyPI and PyPI

# Only activate if the v* tag is pushed.
on:
  push:
    tags:
    - v*

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install twine
      run: >-
        python -m pip install -U twine wheel setuptools

    - name: Build a tar ball
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Verify the distributions
      run: twine check dist/*

    - name: Publish distribution to Test PyPI
      # Do not upload the package from forked repository.
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')  && github.repository == 'toshihikoyanase/mong'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository-url: https://test.pypi.org/legacy/
        attestations: false

    - name: Publish distribution to PyPI
      # Do not upload the package from forked repository.
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')  && github.repository == 'toshihikoyanase/mong'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        attestations: false
